[package]
name = "move-links"
version = "0.1.0"
authors = ["Adolin <benmeft0@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-clean = "0.1.0"
clap = "2.33.3"
